CREATE TABLE IF NOT EXISTS adapters (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    adapterKey VARCHAR(128) NOT NULL,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    synced TIMESTAMP,
    CONSTRAINT unique_adapter_key UNIQUE (adapterKey),
    CONSTRAINT unique_adapter_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS adapterConfiguration (
    id SERIAL PRIMARY KEY,
    adapterId BIGINT UNSIGNED NOT NULL,
    configKey VARCHAR(255) NOT NULL,
    configValue VARCHAR(255) NOT NULL,
    CONSTRAINT unique_config_per_adapter UNIQUE (adapterId, configKey),
    FOREIGN KEY (adapterId) REFERENCES adapters(id) ON DELETE CASCADE,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);